-- ============================================================
-- H1B Sponsor Intelligence Platform
-- Data Quality & Pipeline Validation
-- ============================================================


-- 1. RAW row count
SELECT COUNT(*) AS RAW_ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 2. RAW key-field completeness
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(EMPLOYER_NAME) AS EMPLOYER_NAME_PRESENT,
    COUNT(TAX_ID) AS TAX_ID_PRESENT,
    COUNT(INDUSTRY_NAICS_CODE) AS INDUSTRY_PRESENT,
    COUNT(PETITIONER_CITY) AS CITY_PRESENT,
    COUNT(PETITIONER_STATE) AS STATE_PRESENT,
    COUNT(PETITIONER_ZIP_CODE) AS ZIP_PRESENT
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 3. Check uniqueness of source line identifier
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT LINE_BY_LINE) AS DISTINCT_LINE_IDS
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 4. Validate Silver row count
SELECT COUNT(*) AS SILVER_ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN;


-- 5. Silver must not contain missing employer names
SELECT COUNT(*) AS NULL_EMPLOYER_NAMES
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN
WHERE EMPLOYER_NAME IS NULL
   OR TRIM(EMPLOYER_NAME) = '';


-- 6. Validate key numeric fields
SELECT
    COUNT_IF(NEW_EMPLOYMENT_APPROVAL IS NULL) AS NULL_NEW_APPROVAL,
    COUNT_IF(NEW_EMPLOYMENT_DENIAL IS NULL) AS NULL_NEW_DENIAL,
    COUNT_IF(CONTINUATION_APPROVAL IS NULL) AS NULL_CONT_APPROVAL,
    COUNT_IF(CONTINUATION_DENIAL IS NULL) AS NULL_CONT_DENIAL
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN;


-- 7. Confirm fiscal year values
SELECT
    FISCAL_YEAR,
    COUNT(*) AS ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN
GROUP BY FISCAL_YEAR
ORDER BY FISCAL_YEAR;


-- 8. Validate GOLD employer summary row count
SELECT COUNT(*) AS GOLD_EMPLOYER_SUMMARY_ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY;


-- 9. Validate GOLD petition total calculations
SELECT COUNT(*) AS INVALID_TOTAL_PETITION_ROWS
FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY
WHERE TOTAL_PETITIONS <> TOTAL_APPROVALS + TOTAL_DENIALS;


-- 10. Confirm GOLD aggregate totals match SILVER source totals
WITH silver_totals AS (
    SELECT
        SUM(
            COALESCE(NEW_EMPLOYMENT_APPROVAL, 0)
            + COALESCE(CONTINUATION_APPROVAL, 0)
            + COALESCE(CHANGE_SAME_EMPLOYER_APPROVAL, 0)
            + COALESCE(NEW_CONCURRENT_APPROVAL, 0)
            + COALESCE(CHANGE_EMPLOYER_APPROVAL, 0)
            + COALESCE(AMENDED_APPROVAL, 0)
        ) AS SILVER_TOTAL_APPROVALS,

        SUM(
            COALESCE(NEW_EMPLOYMENT_DENIAL, 0)
            + COALESCE(CONTINUATION_DENIAL, 0)
            + COALESCE(CHANGE_SAME_EMPLOYER_DENIAL, 0)
            + COALESCE(NEW_CONCURRENT_DENIAL, 0)
            + COALESCE(CHANGE_EMPLOYER_DENIAL, 0)
            + COALESCE(AMENDED_DENIAL, 0)
        ) AS SILVER_TOTAL_DENIALS

    FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN
),

gold_totals AS (
    SELECT
        SUM(TOTAL_APPROVALS) AS GOLD_TOTAL_APPROVALS,
        SUM(TOTAL_DENIALS) AS GOLD_TOTAL_DENIALS

    FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY
)

SELECT
    SILVER_TOTAL_APPROVALS,
    GOLD_TOTAL_APPROVALS,
    SILVER_TOTAL_APPROVALS - GOLD_TOTAL_APPROVALS
        AS APPROVAL_TOTAL_DIFFERENCE,
    SILVER_TOTAL_DENIALS,
    GOLD_TOTAL_DENIALS,
    SILVER_TOTAL_DENIALS - GOLD_TOTAL_DENIALS
        AS DENIAL_TOTAL_DIFFERENCE

FROM silver_totals
CROSS JOIN gold_totals;
