-- ============================================================
-- H1B Sponsor Intelligence Platform
-- Data Quality & Pipeline Validation
-- ============================================================


-- 1. RAW row count
SELECT COUNT(*) AS RAW_ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 2. RAW key-field completeness
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(EMPLOYER_NAME) AS EMPLOYER_NAME_PRESENT,
    COUNT(TAX_ID) AS TAX_ID_PRESENT,
    COUNT(INDUSTRY_NAICS_CODE) AS INDUSTRY_PRESENT,
    COUNT(PETITIONER_CITY) AS CITY_PRESENT,
    COUNT(PETITIONER_STATE) AS STATE_PRESENT,
    COUNT(PETITIONER_ZIP_CODE) AS ZIP_PRESENT
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 3. Check uniqueness of source line identifier
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT LINE_BY_LINE) AS DISTINCT_LINE_IDS
FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW;


-- 4. Validate Silver row count
SELECT COUNT(*) AS SILVER_ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN;


-- 5. Silver must not contain missing employer names
SELECT COUNT(*) AS NULL_EMPLOYER_NAMES
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN
WHERE EMPLOYER_NAME IS NULL
   OR TRIM(EMPLOYER_NAME) = '';


-- 6. Validate key numeric fields
SELECT
    COUNT_IF(NEW_EMPLOYMENT_APPROVAL IS NULL) AS NULL_NEW_APPROVAL,
    COUNT_IF(NEW_EMPLOYMENT_DENIAL IS NULL) AS NULL_NEW_DENIAL,
    COUNT_IF(CONTINUATION_APPROVAL IS NULL) AS NULL_CONT_APPROVAL,
    COUNT_IF(CONTINUATION_DENIAL IS NULL) AS NULL_CONT_DENIAL
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN;


-- 7. Confirm fiscal year values
SELECT
    FISCAL_YEAR,
    COUNT(*) AS ROW_COUNT
FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN
GROUP BY FISCAL_YEAR
ORDER BY FISCAL_YEAR;