-- ============================================================
-- H1B Sponsor Intelligence Platform
-- SILVER Layer: Clean and Standardize RAW Data
-- ============================================================


CREATE OR REPLACE TABLE
    H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN AS

SELECT
    TRY_TO_NUMBER(LINE_BY_LINE) AS LINE_BY_LINE,
    TRY_TO_NUMBER(FISCAL_YEAR) AS FISCAL_YEAR,

    TRIM(EMPLOYER_NAME) AS EMPLOYER_NAME,
    TRIM(TAX_ID) AS TAX_ID,
    TRIM(INDUSTRY_NAICS_CODE) AS INDUSTRY_NAICS_CODE,
    TRIM(PETITIONER_CITY) AS PETITIONER_CITY,
    TRIM(PETITIONER_STATE) AS PETITIONER_STATE,
    TRIM(PETITIONER_ZIP_CODE) AS PETITIONER_ZIP_CODE,

    TRY_TO_NUMBER(REPLACE(NEW_EMPLOYMENT_APPROVAL, ',', ''))
        AS NEW_EMPLOYMENT_APPROVAL,

    TRY_TO_NUMBER(REPLACE(NEW_EMPLOYMENT_DENIAL, ',', ''))
        AS NEW_EMPLOYMENT_DENIAL,

    TRY_TO_NUMBER(REPLACE(CONTINUATION_APPROVAL, ',', ''))
        AS CONTINUATION_APPROVAL,

    TRY_TO_NUMBER(REPLACE(CONTINUATION_DENIAL, ',', ''))
        AS CONTINUATION_DENIAL,

    TRY_TO_NUMBER(REPLACE(CHANGE_WITH_SAME_EMPLOYER_APPROVAL, ',', ''))
        AS CHANGE_WITH_SAME_EMPLOYER_APPROVAL,

    TRY_TO_NUMBER(REPLACE(CHANGE_WITH_SAME_EMPLOYER_DENIAL, ',', ''))
        AS CHANGE_WITH_SAME_EMPLOYER_DENIAL,

    TRY_TO_NUMBER(REPLACE(NEW_CONCURRENT_APPROVAL, ',', ''))
        AS NEW_CONCURRENT_APPROVAL,

    TRY_TO_NUMBER(REPLACE(NEW_CONCURRENT_DENIAL, ',', ''))
        AS NEW_CONCURRENT_DENIAL,

    TRY_TO_NUMBER(REPLACE(CHANGE_OF_EMPLOYER_APPROVAL, ',', ''))
        AS CHANGE_OF_EMPLOYER_APPROVAL,

    TRY_TO_NUMBER(REPLACE(CHANGE_OF_EMPLOYER_DENIAL, ',', ''))
        AS CHANGE_OF_EMPLOYER_DENIAL,

    TRY_TO_NUMBER(REPLACE(AMENDED_APPROVAL, ',', ''))
        AS AMENDED_APPROVAL,

    TRY_TO_NUMBER(REPLACE(AMENDED_DENIAL, ',', ''))
        AS AMENDED_DENIAL

FROM H1B_SPONSOR_INTELLIGENCE.RAW.H1B_EMPLOYER_RAW

-- Employer is required for employer-level sponsorship analytics
WHERE EMPLOYER_NAME IS NOT NULL;
