-- ============================================================
-- H1B Sponsor Intelligence Platform
-- GOLD Layer: Business-Ready Analytics Views
-- ============================================================


CREATE SCHEMA IF NOT EXISTS H1B_SPONSOR_INTELLIGENCE.GOLD;


-- ============================================================
-- 1. Employer-level sponsorship summary
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY AS

WITH employer_totals AS (
    SELECT
        FISCAL_YEAR,
        EMPLOYER_NAME,
        TAX_ID,
        INDUSTRY_NAICS_CODE,
        PETITIONER_CITY,
        PETITIONER_STATE,
        PETITIONER_ZIP_CODE,

        SUM(NEW_EMPLOYMENT_APPROVAL) AS NEW_EMPLOYMENT_APPROVALS,
        SUM(NEW_EMPLOYMENT_DENIAL) AS NEW_EMPLOYMENT_DENIALS,
        SUM(CONTINUATION_APPROVAL) AS CONTINUATION_APPROVALS,
        SUM(CONTINUATION_DENIAL) AS CONTINUATION_DENIALS,
        SUM(CHANGE_SAME_EMPLOYER_APPROVAL)
            AS CHANGE_SAME_EMPLOYER_APPROVALS,
        SUM(CHANGE_SAME_EMPLOYER_DENIAL)
            AS CHANGE_SAME_EMPLOYER_DENIALS,
        SUM(NEW_CONCURRENT_APPROVAL) AS NEW_CONCURRENT_APPROVALS,
        SUM(NEW_CONCURRENT_DENIAL) AS NEW_CONCURRENT_DENIALS,
        SUM(CHANGE_EMPLOYER_APPROVAL) AS CHANGE_EMPLOYER_APPROVALS,
        SUM(CHANGE_EMPLOYER_DENIAL) AS CHANGE_EMPLOYER_DENIALS,
        SUM(AMENDED_APPROVAL) AS AMENDED_APPROVALS,
        SUM(AMENDED_DENIAL) AS AMENDED_DENIALS

    FROM H1B_SPONSOR_INTELLIGENCE.SILVER.H1B_EMPLOYER_CLEAN

    GROUP BY
        FISCAL_YEAR,
        EMPLOYER_NAME,
        TAX_ID,
        INDUSTRY_NAICS_CODE,
        PETITIONER_CITY,
        PETITIONER_STATE,
        PETITIONER_ZIP_CODE
),

sponsor_metrics AS (
    SELECT
        *,

        NEW_EMPLOYMENT_APPROVALS
            + CONTINUATION_APPROVALS
            + CHANGE_SAME_EMPLOYER_APPROVALS
            + NEW_CONCURRENT_APPROVALS
            + CHANGE_EMPLOYER_APPROVALS
            + AMENDED_APPROVALS AS TOTAL_APPROVALS,

        NEW_EMPLOYMENT_DENIALS
            + CONTINUATION_DENIALS
            + CHANGE_SAME_EMPLOYER_DENIALS
            + NEW_CONCURRENT_DENIALS
            + CHANGE_EMPLOYER_DENIALS
            + AMENDED_DENIALS AS TOTAL_DENIALS

    FROM employer_totals
)

SELECT
    *,
    TOTAL_APPROVALS + TOTAL_DENIALS AS TOTAL_PETITIONS,
    ROUND(
        DIV0(TOTAL_APPROVALS, TOTAL_APPROVALS + TOTAL_DENIALS) * 100,
        2
    ) AS APPROVAL_RATE_PERCENT,
    ROUND(
        DIV0(TOTAL_DENIALS, TOTAL_APPROVALS + TOTAL_DENIALS) * 100,
        2
    ) AS DENIAL_RATE_PERCENT

FROM sponsor_metrics;


-- ============================================================
-- 2. Top sponsors by total approvals
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.TOP_SPONSORS_BY_APPROVALS AS

SELECT
    FISCAL_YEAR,
    EMPLOYER_NAME,
    INDUSTRY_NAICS_CODE,
    PETITIONER_CITY,
    PETITIONER_STATE,
    TOTAL_APPROVALS,
    TOTAL_DENIALS,
    TOTAL_PETITIONS,
    APPROVAL_RATE_PERCENT,
    RANK() OVER (
        PARTITION BY FISCAL_YEAR
        ORDER BY TOTAL_APPROVALS DESC
    ) AS APPROVAL_RANK

FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY

WHERE TOTAL_APPROVALS > 0;


-- ============================================================
-- 3. Sponsors with the highest denial volume
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.TOP_SPONSORS_BY_DENIALS AS

SELECT
    FISCAL_YEAR,
    EMPLOYER_NAME,
    INDUSTRY_NAICS_CODE,
    PETITIONER_CITY,
    PETITIONER_STATE,
    TOTAL_APPROVALS,
    TOTAL_DENIALS,
    TOTAL_PETITIONS,
    DENIAL_RATE_PERCENT,
    RANK() OVER (
        PARTITION BY FISCAL_YEAR
        ORDER BY TOTAL_DENIALS DESC
    ) AS DENIAL_RANK

FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY

WHERE TOTAL_DENIALS > 0;


-- ============================================================
-- 4. State-level sponsorship summary
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.SPONSORSHIP_BY_STATE AS

SELECT
    FISCAL_YEAR,
    PETITIONER_STATE,
    COUNT(DISTINCT EMPLOYER_NAME) AS EMPLOYER_COUNT,
    SUM(TOTAL_APPROVALS) AS TOTAL_APPROVALS,
    SUM(TOTAL_DENIALS) AS TOTAL_DENIALS,
    SUM(TOTAL_PETITIONS) AS TOTAL_PETITIONS,
    ROUND(DIV0(SUM(TOTAL_APPROVALS), SUM(TOTAL_PETITIONS)) * 100, 2)
        AS APPROVAL_RATE_PERCENT

FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY

GROUP BY
    FISCAL_YEAR,
    PETITIONER_STATE;


-- ============================================================
-- 5. City-level sponsorship summary
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.SPONSORSHIP_BY_CITY AS

SELECT
    FISCAL_YEAR,
    PETITIONER_STATE,
    PETITIONER_CITY,
    COUNT(DISTINCT EMPLOYER_NAME) AS EMPLOYER_COUNT,
    SUM(TOTAL_APPROVALS) AS TOTAL_APPROVALS,
    SUM(TOTAL_DENIALS) AS TOTAL_DENIALS,
    SUM(TOTAL_PETITIONS) AS TOTAL_PETITIONS,
    ROUND(DIV0(SUM(TOTAL_APPROVALS), SUM(TOTAL_PETITIONS)) * 100, 2)
        AS APPROVAL_RATE_PERCENT

FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY

GROUP BY
    FISCAL_YEAR,
    PETITIONER_STATE,
    PETITIONER_CITY;


-- ============================================================
-- 6. Industry-level sponsorship summary
-- ============================================================

CREATE OR REPLACE VIEW
    H1B_SPONSOR_INTELLIGENCE.GOLD.SPONSORSHIP_BY_INDUSTRY AS

SELECT
    FISCAL_YEAR,
    INDUSTRY_NAICS_CODE,
    COUNT(DISTINCT EMPLOYER_NAME) AS EMPLOYER_COUNT,
    SUM(TOTAL_APPROVALS) AS TOTAL_APPROVALS,
    SUM(TOTAL_DENIALS) AS TOTAL_DENIALS,
    SUM(TOTAL_PETITIONS) AS TOTAL_PETITIONS,
    ROUND(DIV0(SUM(TOTAL_APPROVALS), SUM(TOTAL_PETITIONS)) * 100, 2)
        AS APPROVAL_RATE_PERCENT

FROM H1B_SPONSOR_INTELLIGENCE.GOLD.H1B_EMPLOYER_SPONSORSHIP_SUMMARY

GROUP BY
    FISCAL_YEAR,
    INDUSTRY_NAICS_CODE;
